### PR TITLE
Update for Fastify v5

### PR DESCRIPTION
**Pull request by gurgunday**

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
This does not need to be bumped, this module can support new versions of Node.js

**Comment by gurgunday** [comment]
Ok

What about moving to tap, from tape?

**Comment by gurgunday** [comment]
@Fdawgs can you add to the workflows a passable option that corresponds to sth like “also test on” to add additional node versions?

**Comment by mcollina** [comment]
> What about moving to tap, from tape?

nope, tape works great across the supported version of Node.js

**Comment by Fdawgs** [comment]
> @Fdawgs can you add to the workflows a passable option that corresponds to sth like “also test on” to add additional node versions?

Kind of goes against the point of the workflows, which was to create a standardised workflow that had minimal config, so that all plugins had to adhere to the same testing.

**Comment by mcollina** [comment]
This is not a plugin.

**Review by Fdawgs — APPROVED** [review]

**Comment by mcollina** [comment]
this does not need to go to `next`.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
